### ISSUE TITLE
[bug] HTTP/HTTPS to WS/WSS Protocol string change cause the passed commands with URLs in it to fail

### ISSUE THREAD

**Issue by bobab12** [renoki-co/php-k8s#111]
Currently KubernetesCluster::makeWsRequest() replaces too much when transforming from https:// -> wss:// and http:// -> ws://. For example, when calling exec on a pod with any URL in the command, these URLs are also transformed causing the command to fail.

**Comment by rennokki** [comment]
@bobab12 The latest patch for `2.9` should work right now.
