### ISSUE TITLE
Container  Argument #1 ($attributes) must be of type array

### ISSUE THREAD

**Issue by RispyCZ** [renoki-co/php-k8s#227]
When I try create new deployment I got this error

RenokiCo\\PhpK8s\\K8s::container(): Argument #1 ($attributes) must be of type array, RenokiCo\\PhpK8s\\KubernetesCluster given, called in /home/rispy/Dokumenty/api-panel/vendor/renoki-co/php-k8s/src/KubernetesCluster.php on line 392

Here is code that I'm trying to run (It's from docs)

        $container = K8s::container()
            ->setName('mysql')
            ->setImage('mysql', '5.7')
            ->setPorts([
                ['name' => 'mysql', 'protocol' => 'TCP', 'containerPort' => 3306],
            ]);

        $pod = K8s::pod()
            ->setName('mysql')
            ->setLabels(['tier' => 'backend']) // needs deployment-name: mysql so that ->getPods() can work
            ->setContainers([$container]);

        $dep = K8s::getCluster()
            ->deployment()
            ->setName('mysql')
            ->setSelectors(['matchLabels' => ['tier' => 'backend']])
            ->setReplicas(1)
            ->setTemplate($pod)
            ->create();
    }

**Comment by rennokki** [comment]
@RispyCZ Did you make sure the `K8s` class is actually `\RenokiCo\PhpK8s\K8s`?

**Comment by RispyCZ** [comment]
I'm using laravel and this is my class import  use RenokiCo\LaravelK8s\LaravelK8sFacade as K8s

**Comment by elyash14** [comment]
Hi everyone. I have a problem like this. any solution?!

**Comment by rennokki** [comment]
Use the facade for the cluster interaction and the original `K8s` for declaring static content:

```php
use RenokiCo\LaravelK8s\LaravelK8sFacade as K8sFacade;
use RenokiCo\PhpK8s\K8s;

$container = K8s::container()->...;

K8sFacade::deploy()->...($container)
```

This issue should have been opened on https://github.com/renoki-co/laravel-php-k8s
