### ISSUE TITLE
cURL ssl verification failed

### ISSUE THREAD

**Issue by sandweel** [renoki-co/php-k8s#232]
First of all thank you for this module. Very helpful.

The question is how to skip SSL verification for cURL in this module?
I'm using:

>         $cluster = KubernetesCluster::fromKubeConfigVariable('KUBECONFIG_PATH');
>         $ns = $cluster->getAllNamespaces();

Error:

```
GuzzleHttp\Exception\RequestException
cURL error 1: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /api/v1/namespaces?pretty=1
```

**Comment by rennokki** [comment]
Documentation: https://php-k8s.renoki.org/getting-started/authentication#ssl-tls-support
