### ISSUE TITLE
Ability to apply labels and taints to Node

### ISSUE THREAD

**Issue by AlexGodbehere** [renoki-co/php-k8s#240]
First off, thanks for creating this package, it makes management of my cluster infinitely simpler.

I'm trying to use the package to apply labels and taints to my Node. I can't find any reference to taints in the codebase so I assume that they're not supported, however when I try to apply a label to my node it simply doesn't show up - no error.

Am I missing something?

```php
$k8sNode = $cluster->getNodeByName($nodeHostname);
$k8sNode->setLabels(
    [
        'nodeUuid' => 'test',
    ]
);
```

**Comment by rennokki** [comment]
Any class is able to retrieve or set parameters not defined in the PHP classes with custom setters/getters: https://php-k8s.renoki.org/resources/base-resource/cluster-methods

**Comment by Ekion-1** [comment]
Thanks for the response but that doesn't answer my question. When I'm applying the `setLabels` method the labels are not applied to the node. Can you advise how I might go about debugging this?

**Comment by Ekion-1** [comment]
Solved this. I forgot to add `->update()` to the end of the `setLabels()` chain. It should read:

```php
>>> $k8sNode = $cluster->getNodeByName('gf1np5n9')->setLabels(['test' => 'test'])->update();
=> true
```
