### ISSUE TITLE
Kind:Issuer

### ISSUE THREAD

**Issue by sandweel** [renoki-co/php-k8s#242]
Method: `$cluster->fromTemplatedYamlFile` just skipping kubernetes resource **Issuer**.
I didn't find information about **Issuer** in your documentation.
Would be great if you add possibility to create this resource type.

**Comment by rennokki** [comment]
`Issuer` kind is a custom kind right? It isn't a Core Kubernetes resource.

**Comment by sandweel** [comment]
> `Issuer` kind is a custom kind right? It isn't a Core Kubernetes resource.

Yes it is [cert-manager](https://cert-manager.io/)

**Comment by rennokki** [comment]
@sandweel This package contains only kinds that are in the Kubernetes core, but you can create your own classes and make them interact with your `$cluster` variable: https://php-k8s.renoki.org/advanced/create-classes-for-crds
