### ISSUE TITLE
Call to undefined function RenokiCo\PhpK8s\yaml_parse()

### ISSUE THREAD

**Issue by buzanits** [renoki-co/php-k8s#249]
When calling `fromYamlFile()` it raises

`Call to undefined function RenokiCo\PhpK8s\yaml_parse() `

I could fix it by changing `yaml_parse($yaml, -1)` to `\yaml_parse($yaml, -1)` in line 30 in K8s.php but I don't know if this will break something else...

**Comment by rennokki** [comment]
Install the PHP YAML extension.
