### ISSUE TITLE
Support for SelfSubjectAccessReview and SelfSubjectRulesReview

### ISSUE THREAD

**Issue by cscognamiglio** [renoki-co/php-k8s#319]
Hello,

I am trying to build requests for the resource SelfSubjectAccessReview and SelfSubjectRulesReview but it looks like php-k8s does not support this out of the box.
Is it possible to execute this request by using php-k8s somehow or support for it needs to be developed?

**Comment by rennokki** [comment]
@cscognamiglio This can be done with Macros if you need something that's not implemented: https://php-k8s.renoki.org/advanced/macros
