### ISSUE TITLE
Initializing k8s object gives null

### ISSUE THREAD

**Issue by Evacch** [renoki-co/php-k8s#41]
Hi, I would like to ask why is it returning null object here, I was trying to get all services which I have verified it with Postman and it works perfectly fine but when I tried to use the PHP client here, it show me an error that the getAllServices() function run on null. The code below is how initialize the k8s object. Did I miss out anything?

`$cluster = new KubernetesCluster("https://_my-k8s-ip_", _my-k8s-port_);
$token = "_my-service-account-token_";
$cluster->withoutSSLChecks()->withToken($token);

function list_all_services() {
  return json_encode($cluster);
  // $services = $cluster->getAllServices('training-lab');
}`

**Comment by rennokki** [comment]
You will need to run `$cluster->getAllServices()`. I want to know more about the context of your application. You can check how the function is tested: https://github.com/renoki-co/php-k8s/blob/master/tests/ServiceTest.php#L80-L91

**Comment by Evacch** [comment]
Hi I did try running the function and this is what I get.
![image](https://user-images.githubusercontent.com/26452088/98084761-4c20d280-1eb7-11eb-89db-fae55c43fabf.png)

the object looks like it's a null object.

**Comment by Evacch** [comment]
@rennokki I have resolved this issue myself now, it's because of how I declare the object wrongly. Thank you for your prompt response.
