### ISSUE TITLE
How to set Service type to NodePort?

### ISSUE THREAD

**Issue by Evacch** [renoki-co/php-k8s#43]
Hi, I was trying to create a service and I tried with `->setType('NodePort')` but it's not working and I get to create a service with the default type which is "ClusterIP", May I know what is the correct way of setting the type of a service?
![image](https://user-images.githubusercontent.com/26452088/98339407-a13f1e80-2046-11eb-8cb9-ba3f4b9d9e41.png)

**Comment by rennokki** [comment]
The value is found under the `spec` field, so you should use `->setSpec('type', 'NodePort')`
