### ISSUE TITLE
DO NOT USE THIS PACKAGE

### ISSUE THREAD

**Issue by ro0NL** [renoki-co/php-k8s#439]
cc @rennokki

**Comment by cuppett** [comment]
FWIW, I've been keeping a discrete main branch in a stopgap fork here:

https://github.com/cuppett/php-k8s/commits/main/

And including this separately in composer.json:

```json
{
    "require": {
        "renoki-co/php-k8s": "dev-main"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cuppett/php-k8s"
        }
    ]
}
```

It has a couple other nits included as well to consolidate some of the activity and keep up with other activity/bumps. 

Not looking to go alone, but would be willing to help a bit with upkeep in renoki-co/php-k8s if wanted. This package has worked well for me.
