### ISSUE TITLE
vierbergenlars/php-semver

### ISSUE THREAD

**Issue by LrMiLoef** [renoki-co/php-k8s#50]
Hi, 

is it possible to change the dependency of **vierbergenlars/php-semver** to a stable release instead of **dev-master**?

**Comment by rennokki** [comment]
Hey, can't remember why I chose dev-master, I'll check out and use a stable version.

**Comment by rennokki** [comment]
Tagged https://github.com/renoki-co/php-k8s/releases/tag/1.14.0
