### ISSUE TITLE
Applying `HasLabels` trait to all children of `K8sResource`

### ISSUE THREAD

**Issue by MujibAzizi** [renoki-co/php-k8s#52]
Hi @rennokki — first of all; you've got a great project going on here! I really like the work you've done so far.

Is there a specific reason you have not added the `HasLabels` trait to all classes/resources in https://github.com/renoki-co/php-k8s/blob/master/src/Kinds/ ? All of these resources support Labels, thus adding the `HasLabels` trait to the `https://github.com/renoki-co/php-k8s/blob/master/src/Kinds/K8sResource.php` file would make the usage consistent.

If you don't have any objections, I'd be more than happy to create a PR for this.

**Comment by rennokki** [comment]
I have tried for some to add labels and the api simply won't return them when i retrieve them back 🤔 You can check the tests as well.

A PR would be welcomed! ☺️

**Comment by MujibAzizi** [comment]
I'll have a go and try it out. 

My environment is Docker Desktop for Mac with Kubernetes v1.18.8.
