### ISSUE TITLE
getPods not work

### ISSUE THREAD

**Issue by Roken120** [renoki-co/php-k8s#61]
Hello,
$dep = $cluster->getDeploymentByName('whoami');
var_dump($dep->getPods());
Result this : object(RenokiCo\PhpK8s\ResourcesList)#939 (1) { ["items":protected]=> array(0) { } }
I have 4 pods in whoami deployment how i can get all pod of deployment ?
Can you help me ?
I can scale and get the number of replicas maybe i can get the pod info of deployment

**Comment by rennokki** [comment]
To make this work, you have to attach a `deployment-name` pod label on the pod template in deployment configuration: https://github.com/renoki-co/php-k8s/blob/1.19.0/tests/DeploymentTest.php#L94

This is the only workaround. The other ones are `statefulset-name` that should be used on StatefulSet objects.
