### ISSUE TITLE
Feature Request: CRD Support

### ISSUE THREAD

**Issue by fuel-wlightning** [renoki-co/php-k8s#63]
Hi,
It would be nice to be able to support CRDs such as those provided by cert-manager and Itsio in a generic way. Alternately a documented way to create a package that registers those CRDs for use with this library.

**Comment by rennokki** [comment]
I was thinking about it while I had to write some custom CRDs for a project that uses [Agones](https://agones.dev/site/docs), but no docs are currently available. Perhaps it's a good start to write some 🤔

**Comment by fuel-wlightning** [comment]
Looking at a couple of CRDs, it looks like the cluster has a few with openAPIV3Schema on it.

For instance on one of my clusters I ran `kubectl get crd` for a list and then did `kubectl get crd -o yaml certificates.certmanager.k8s.io` which then had the schema definition.

**Comment by rennokki** [comment]
I can only show an example for the Issuer in `cert-manager.io/v1`:

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: sandbox
spec:
  selfSigned: {}
```
```php
namespace My\Namespace;

use RenokiCo\PhpK8s\Contracts\InteractsWithK8sCluster;
use RenokiCo\PhpK8s\Kinds\K8sResource;

class Issuer extends K8sResource implements InteractsWithK8sCluster
{
    /**
     * The resource Kind parameter.
     *
     * @var null|string
     */
    protected static $kind = 'Issuer';

    /**
     * Wether the resource has a namespace.
     *
     * @var bool
     */
    protected static $namespaceable = true;

    /**
     * The default version for the resource.
     *
     * @var string
     */
    protected static $defaultVersion = 'cert-manager.io/v1';
}
```

**Comment by rennokki** [comment]
Also, there are a lot of [traits](https://github.com/renoki-co/php-k8s/tree/master/src/Traits) and [contracts](https://github.com/renoki-co/php-k8s/tree/master/src/Contracts) that can be added. But it seems like docs need a little bit of revamping. 🤓

**Comment by rennokki** [comment]
https://github.com/renoki-co/php-k8s/blob/revamp/docs/docs/CRDS.md
