### ISSUE TITLE
Can nont create namespace 

### ISSUE THREAD

**Issue by muhammedbuvaydani** [renoki-co/php-k8s#92]
```
$cluster =new KubernetesCluster('http://127.0.0.1:8001');
 $ns = $cluster->namespace()->setName("$name")->create();
```
and  I have this error 
RenokiCo\PhpK8s\Exceptions\KubernetesAPIException: Client error: `POST http://127.0.0.1:8001/api/v1/namespaces?pretty=1` resulted in a `422 Unprocessable Entity` response: { "kind": "Status", "apiVersion": "v1", "metadata": { }, "status": "Failure", "message": "Namespace \"T (truncated...) in

**Comment by rennokki** [comment]
Try to catch the issue and see what's going on:

```php
$cluster = new KubernetesCluster('http://127.0.0.1:8001');

try {
    $ns = $cluster->namespace()->setName("$name")->create();
} catch (\RenokiCo\PhpK8s\Exceptions\KubernetesAPIException $e) {
    var_dump($e->getPayload());
}
```

**Comment by muhammedbuvaydani** [comment]
oh yes  , thanks for your help , actually the problem is that  I am  passing the name with capita latter , it is working now ,thanks
